services:
  php-api:
    container_name: php-api
    build:
      context: .
    volumes:
      - ./api:/var/www/html
    ports:
      - "80"
    expose:
      - "80"
    networks:
      - internal

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - php-api
    networks:
      - internal
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.php-api.entrypoints=http" 
      - "traefik.http.routers.php-api.rule=Host(`php.cloud.local`)"
      - "traefik.http.middlewares.php-api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.php-api.middlewares=php-api-https-redirect"
      - "traefik.http.routers.php-api-secure.rule=Host(`php.cloud.local`)"
      - "traefik.http.routers.php-api-secure.entrypoints=https"
      - "traefik.http.routers.php-api-secure.tls=true"
      - "traefik.http.services.php-api-secure.loadbalancer.server.port=8080"

networks:
  internal:
    driver: bridge
    external: true
    
  traefik-proxy:
    external: true